# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "ws"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"
engines:
template:
  template_toolkit:
    start_tag: '[%'
    end_tag:   '%]'



plugins:
  Emailesque:
    from: splineapi@gmail.com
    # for gmail...
    ssl: 1
    driver: smtp
    host: smtp.gmail.com
    port: 465
    user: splineapi@gmail.com
    pass: splinepassword
  Database:
    driver: SQLite
    database: 'spline.sqlite'
    host: 'localhost'
    connection_check_threshold: 20
    dbi_params:
        RaiseError: 1
        AutoCommit: 1
    on_connect_do: ["CREATE TABLE IF NOT EXISTS api_users (api_token VARCHAR(100) UNIQUE, email VARCHAR(100) UNIQUE, requests INTEGER DEFAULT 0, request_limit INTEGER DEFAULT 1000);","INSERT OR IGNORE INTO api_users(api_token,email) VALUES ('b57fc7d6e6034c8a3c7d5ffa7cb54d40fd276db3b2b92852f50a6d6fea4d8a93', 'splineapi@gmail.com');", "CREATE TABLE IF NOT EXISTS api_history (api_token VARCHAR(100), request VARCHAR(50), cost INTEGER, date VARCHAR(50));"]
